version: "3"
services:
  api:
    build:
      dockerfile: "Dockerfile"
      context: "."
    volumes:
      - ./backend/images/:/data/images 
    networks:
      - apiserver
    restart: unless-stopped  
networks:
    apiserver:
